# Generated by Django 4.2.20 on 2025-06-17 12:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cilindro',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_de_llegada', models.DateField(default=datetime.date.today)),
                ('defectuoso', models.BooleanField(default=False)),
                ('lleno', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Normal', 'Normal'), ('Especial', 'Especial')], max_length=255)),
                ('fecha_UT', models.DateField(blank=True, null=True)),
                ('fecha_PC', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(choices=[('Tecnico', 'Tecnico'), ('Jefe de Servicio', 'Jefe de Servicio')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('defecto', models.TextField(max_length=255)),
                ('cilindro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cilindro')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante_Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cilindroE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes_entrada', to='app.cilindro')),
                ('cilindroS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes_salida', to='app.cilindro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante_Abastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cant_cilindros', models.IntegerField()),
                ('proveedor', models.CharField(max_length=50)),
                ('trabajador_recibio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='cilindro',
            name='asign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente'),
        ),
    ]
