# Generated by Django 5.1.7 on 2025-03-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_trabajador_correo_remove_trabajador_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('uno', 'Uno'), ('dos', 'Dos')], max_length=255),
        ),
    ]
