# Generated by Django 5.1.7 on 2025-03-20 15:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cliente_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cilindro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fehca_llegada', models.DateField(default=datetime.date.today)),
                ('defectuoso', models.BooleanField(default=False)),
                ('lleno', models.BooleanField(default=True)),
                ('asign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
    ]
