# Generated by Django 5.1.7 on 2025-04-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_trabajador_user_comprobante_abastecimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('especial', 'Especial')], max_length=255),
        ),
    ]
