# Generated by Django 5.1.7 on 2025-04-26 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cilindro',
            name='asign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente'),
        ),
    ]
