# Generated by Django 4.2.20 on 2025-04-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cilindro_asign'),
    ]

    operations = [
        migrations.AddField(
            model_name='cilindro',
            name='num',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero de serie'),
        ),
    ]
