# Generated by Django 4.2.20 on 2025-05-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cilindro_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cilindro',
            name='num',
        ),
        migrations.AlterField(
            model_name='cilindro',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
