# Generated by Django 4.2.20 on 2025-05-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_cilindro_num_alter_cilindro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cilindro',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
