# Generated by Django 4.2.20 on 2025-05-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_cilindro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_PC',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_UT',
            field=models.DateField(blank=True, null=True),
        ),
    ]
