# Generated by Django 4.2.20 on 2025-06-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cliente_fecha_pc_alter_cliente_fecha_ut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cilindro',
            old_name='fehca_llegada',
            new_name='fecha_de_llegada',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Especial', 'Especial')], max_length=255),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='puesto',
            field=models.CharField(choices=[('Tecnico', 'Tecnico'), ('Jefe de Servicio', 'Jefe de Servicio')], max_length=255),
        ),
    ]
