# Generated by Django 4.2.20 on 2025-06-09 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_fehca_llegada_cilindro_fecha_de_llegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante_entrega',
            name='cilindroS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes_salida', to='app.cilindro'),
        ),
    ]
