# Generated by Django 4.2.20 on 2025-06-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_comprobante_entrega_cilindros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante_entrega',
            name='cilindroE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes_entrada', to='app.cilindro'),
        ),
    ]
