# Generated by Django 4.2.20 on 2025-06-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_comprobante_entrega_cilindroe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobante_abastecimiento',
            old_name='trabajador_recivio',
            new_name='trabajador_recibio',
        ),
    ]
